<?php

use \BreakpointDebugging as B;
use \BreakpointDebugging_PHPUnit as BU;

/**
 * Test class for BreakpointDebugging_Exception.
 * Generated by PHPUnit on 2012-09-30 at 16:24:28.
 */
class BreakpointDebugging_ExceptionTest extends \BreakpointDebugging_PHPUnit_FrameworkTestCase
{
    /**
     * @covers \BreakpointDebugging_Exception<extended>
     */
    public function test__construct()
    {
        $previous = new \Exception('Previous message.');
        new \BreakpointDebugging_Exception('Test message.', 1, $previous, 0);
        new \BreakpointDebugging_Exception('Test message.', 1, $previous);
        new \BreakpointDebugging_Exception('Test message.', 1);
        new \BreakpointDebugging_Exception('Test message.');
    }

    /**
     * @covers \BreakpointDebugging_Exception<extended>
     *
     * @expectedException        \BreakpointDebugging_ErrorException
     * @expectedExceptionMessage CLASS=BreakpointDebugging_Exception FUNCTION=__construct ID=101.
     */
    public function test__construct_H()
    {
        $previous = new \Exception('Previous message.');
        // SJIS message.
        new \BreakpointDebugging_Exception("\x95\xB6\x8E\x9A", 1, $previous, 1);
    }

}

?>
